CREATE TABLE IF NOT EXISTS PASSENGER(
	FNAME VARCHAR(15) NOT NULL,
	LNAME VARCHAR(15),
	ADDRESS VARCHAR(30),
	CITY VARCHAR(15),
	COUNTY VARCHAR(15),
	PHONE VARCHAR(15),
	SSN INT PRIMARY KEY,
	BDATE CHAR(10)
);



CREATE TABLE IF NOT EXISTS TRAIN(
	TRAIN_NUMBER INT PRIMARY KEY,
	TRAIN_NAME VARCHAR(25) UNIQUE,
	PREMIUM_FARE DECIMAL(12,2) NOT NULL,
	GENERAL_FARE DECIMAL(12,2) NOT NULL,
	SOURCE_STATION VARCHAR(15) NOT NULL,
	DESTINATION_STATION VARCHAR(15) NOT NULL
);


 
CREATE TABLE IF NOT EXISTS TRAIN_AVAILABLE_DAYS(
	TRAIN_NUMBER INT NOT NULL,
	DAY VARCHAR(10) NOT NULL,

	PRIMARY KEY(TRAIN_NUMBER, DAY),
	FOREIGN KEY(TRAIN_NUMBER) REFERENCES TRAIN(TRAIN_NUMBER) ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS TRAIN_STATUS(
	TRAIN_DAY VARCHAR(15) NOT NULL,
	TRAIN_NAME VARCHAR(25) NOT NULL,
	PREMIUM_SEATS_AVAILABLE INT NOT NULL,
	GENERAL_SEATS_AVAILABLE INT NOT NULL,
	PREMIUM_SEATS_OCCUPIED INT NOT NULL,
	GENERAL_SEATS_OCCUPIED INT NOT NULL,

	PRIMARY KEY(TRAIN_DAY, TRAIN_NAME),
	FOREIGN KEY(TRAIN_NAME) REFERENCES TRAIN(TRAIN_NAME) ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS BOOKED(
	PASSENGER_SSN INT NOT NULL,
	TRAIN_NUMBER INT NOT NULL,
	TICKET_TYPE VARCHAR(15) NOT NULL,
	TICKET_STATUS VARCHAR(15) NOT NULL,

	PRIMARY KEY(PASSENGER_SSN, TRAIN_NUMBER),
	FOREIGN KEY(PASSENGER_SSN) REFERENCES PASSENGER(SSN) ON UPDATE CASCADE,
	FOREIGN KEY(TRAIN_NUMBER) REFERENCES TRAIN(TRAIN_NUMBER) ON UPDATE CASCADE
);



.mode csv
.import Passenger-1.csv PASSENGER
.import Train_status.csv TRAIN_STATUS
.import booked-1.csv BOOKED


INSERT INTO TRAIN VALUES(1, 'Orient Express', 800, 600, 'Paris', 'Istanbul');
INSERT INTO TRAIN VALUES(2, 'Flying Scotsman', 4000, 3500, 'Edinburgh', 'London');
INSERT INTO TRAIN VALUES(3, 'Golden Arrow' , 980, 860, 'Victoria', 'Dover');
INSERT INTO TRAIN VALUES(4, 'Golden Chariot', 4300, 3800, 'Bangalore', 'Goa');
INSERT INTO TRAIN VALUES(5, 'Maharaja Express', 5980, 4510, 'Delhi', 'Mumbai');



INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(1, 'Monday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(1, 'Tuesday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(1, 'Wednesday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(1, 'Thursday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(1, 'Friday');

INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(2, 'Friday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(2, 'Saturday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(2, 'Sunday');

INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(3, 'Monday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(3, 'Tuesday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(3, 'Wednesday');

INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(4, 'Saturday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(4, 'Sunday');

INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(5, 'Wednesday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(5, 'Thursday');
INSERT INTO TRAIN_AVAILABLE_DAYS VALUES(5, 'Friday');

